# Generated by Django 5.0.2 on 2024-02-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('menu_description', models.TextField()),
                ('menu_image', models.ImageField(upload_to='menu_images/')),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
