# Generated by Django 5.0.2 on 2024-02-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(default=2, upload_to='menu_images/'),
            preserve_default=False,
        ),
    ]
