# Generated by Django 5.0.2 on 2024-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_cartitem_deliverycrew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('delivery_crew', 'delivery crew')], default='user', max_length=100),
        ),
    ]
