# Generated by Django 5.0.2 on 2024-02-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
            ],
        ),
    ]
